package utilities;

public class Costanti {
    public static final int Login = 0;                          //Costante Login

    public static final int Logout = 1;                         //Costante Logout
    public static final int Registrazione = 2;                  //Costante Registrazione
    public static final int Cambio_Pswd = 3;                    //Costante Cambio Psqd
    public static final int Add_Vino = 4;                       //Costante Add Vino
    public static final int Mostra_Vini_Produttore = 5;         //Costante Mostra Vini Produttore
    public static final int Ricerca_Vini_Produttore = 6;        //Costante Ricerca Vini Produttore
    public static final int Modifica_Dati_Vini = 7;             //Costante Modifica Dati Vini
    public static final int Modifica_Dati_Vini_Anno = 8;        //Costante Modifica Dati Vini Anno
    public static final int Modifica_Dati_Vini_Prezzo = 9;      //Costante Modifica Dati Vini Prezzo
    public static final int Modifica_Dati_Vini_Soglia = 10;     //Costante Modifica Dati Vini Soglia
    public static final int Modifica_Dati_Vini_Quantita = 11;   //Costante Modifica Dati Vini Quantita
    public static final int Modifica_Dati_Vini_Tutti = 12;      //Costante Modifica Dati Vini Tutti
    public static final int Delete_Vino = 13;                   //Costante Elimina Vino
    public static final int Registrazione_Impiegati = 14;       //Costante Aggiunta Impiegati
    public static final int Add_Report = 15;                    //Costante Add Report
    public static final int Mostra_Vini = 16;                   //Costante Mostra Vini
    public static final int Mostra_Clienti = 17;                //Costante Mostra Clienti
    public static final int Mostra_Offerte = 18;                //Costante Mostra Offerte
    public static final int Mostra_Impiegati = 19;              //Costante Mostra Impiegati
    public static final int Mostra_Ordini = 20;                 //Costante Mostra Ordini
    public static final int Ricerca_Vini = 21;                  //Costante Mostra Vini
    public static final int Ricerca_Clienti = 22;               //Costante Ricerca Clienti
    public static final int Ricerca_Offerte = 23;               //Costante Ricerca Offerte
    public static final int Ricerca_Impiegati = 24;             //Costante Ricerca Impiegati
    public static final int Ricerca_Ordini = 25;                //Costante Ricerca Ordini
    public static final int Elimina_Impiegato = 26;             //Costante Elimina Impiegato
    public static final int Elimina_Offerta = 27;               //Costante Elimina Offerta
    public static final int Mostra_Dettagli_Ordine = 28;        //Costante Mostra Dettagli Ordine
    public static final int Add_Offerta = 29;                   //Costante Add Offerta
    public static final int Modifica_Dati_Offerta = 30;         //Costante Modifica Dati Offerta
    public static final int Modifica_Dati_Offerta_Sconto = 31;  //Costante Modifica Dati Offerta Sconto
    public static final int Modifica_Stato_Ordine = 32;         //Costante Modifica Stato Ordine
    public static final int Mostra_Ordini_Cliente = 33;         //Costante Mostra Ordine Cliente
    public static final int Ricerca_Ordini_Cliente = 34;        //Costante Ricerca Ordini Cliente
    public static final int Add_Preferiti = 35;                 //Costante Add Preferiti
    public static final int Mostra_Preferiti = 36;              //Costante Mostra Preferiti
    public static final int Ricerca_Preferiti = 37;             //Costante Ricerca Preferiti
    public static final int Elimina_Preferiti = 38;             //Costante Elimina Preferiti
    public static final int Add_Recensione = 39;                //Costante Add Recensione
    public static final int Mostra_Recensioni = 40;             //Costante Mostra Recensioni
    public static final int Ricerca_Recensioni = 41;            //Costante Ricerca Recensioni
    public static final int Elimina_Recensioni = 42;            //Costante Elimina Recensioni
    public static final int Add_Carrello = 43;                  //Costante Add Carrello
    public static final int Mostra_Vini_Carrello = 44;          //Costante Mostra Vini Carrello
    public static final int Update_Quantita_Vino = 45;          //Costante Aggiorna Quantita Vino
    public static final int Verifica_Offerte_Vino = 46;         //Costante Verifica Offerte Vino
    public static final int Add_Ordine = 47;                    //Costante Add Ordine
    public static final int Update_Dettagli_ordine = 48;        //Costante Aggiorna Dettagli Ordine
    public static final int Mostra_Ordini_Effettuati = 49;      //Costante Mostra Ordini Effettuati
    public static final int Add_Assistenza = 50;                //Costante Add Assistenza
    public static final int Successo = 200;
    public static final int Fallimento = 201;
    public static final int Bad_Request = 400;
    public static final int Internal_Server_Error = 500;
    public static final int No_Righe = 998;
    public static final int Close_Connection = 999;
}
