package utilities;

public class Costanti {
    public static final int Add_Wine = 0;
    public static final int Update_Wine = 1;
    public static final int Delete_Wine = 2;
    public static final int Get_Vini_Disponibili = 3;
    public static final int Get_Wine_By_Id = 4;
    public static final int Search_Wine = 5;
    public static final int Add_Wine_Review = 6;
    public static final int Get_Wine_Reviews = 7;
    public static final int Add_Carrello = 8;
    public static final int Remove_Carrello = 9;
    public static final int Get_Carrello = 10;
    public static final int Get_Orders_History = 11;
    public static final int Update_Account = 12;
    public static final int Get_Account = 13;
    public static final int Login = 14;
    public static final int Logout = 15;
    public static final int Registrazione = 16;
    public static final int Add_Offerta = 17;
    public static final int Remuovi_Offerta = 18;
    public static final int Mostra_Offerte = 19;
    public static final int Ordini_Spediti = 20;
    public static final int Mostra_Ordini = 21;
    public static final int Mostra_Vini_Da_Ripristinare = 22;
    public static final int Ripristina_Vino = 23;
    public static final int Compra_Vino = 24;
    public static final int Get_Venditori = 25;
    public static final int Vendi_Vino = 26;
    public static final int Show_Ordini_Clienti = 27;
    public static final int Get_All_Wines_Names = 28;
    public static final int Add_Favourite_Wine = 29;
    public static final int Cambio_Pswd = 30;
    public static final int Successo = 200;
    public static final int Fallimento = 201;
    public static final int Bad_Request = 400;
    public static final int Internal_Server_Error = 500;
    public static final int No_Righe = 998;
    public static final int Close_Connection = 999;
}
